# Generated by Django 3.0.8 on 2020-07-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselist',
            options={'verbose_name_plural': 'TODO-LISTS'},
        ),
    ]
